# Generated by Django 5.0.6 on 2024-07-10 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("produtos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_ata", models.CharField(max_length=200, null=True)),
                ("data", models.DateField()),
                (
                    "valor_total_ata",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "valor_total_pedidos",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "valor_restante",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("link_drive", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Geral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_total_atas_ganhas",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "valor_total_pedidos",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "valor_total_restante",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Geral",
            },
        ),
        migrations.CreateModel(
            name="Municipio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.IntegerField()),
                (
                    "unidade",
                    models.CharField(
                        choices=[("un", "un"), ("kg", "kg"), ("gramas", "gramas")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "valor_unitario",
                    models.DecimalField(decimal_places=3, max_digits=20),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("quantidade_restante", models.IntegerField(blank=True, null=True)),
                (
                    "ata",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sistema.ata"
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produtos.produto",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ata",
            name="municipio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="atas",
                to="sistema.municipio",
            ),
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nota_fiscal", models.IntegerField()),
                ("quantidade_pedida", models.IntegerField()),
                (
                    "valor_total_pedido",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("prazo", models.DateField()),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("e", "Em entrega"),
                            ("n", "Não iniciado"),
                            ("f", "Finalizado"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "ata",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sistema.ata"
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sistema.item"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Resumo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resumo", models.TextField()),
                (
                    "ata",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sistema.ata"
                    ),
                ),
            ],
        ),
    ]
