# Generated by Django 5.0.6 on 2024-06-19 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sistema", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="quantidade_restante",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Resumo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resumo", models.TextField()),
                (
                    "ata",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sistema.ata"
                    ),
                ),
            ],
        ),
    ]
