# Generated by Django 5.0.6 on 2024-07-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sistema", "0002_alter_pedido_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("n", "Não iniciado"),
                    ("f", "Finalizado"),
                    ("e", "Em entrega"),
                ],
                max_length=1,
                null=True,
            ),
        ),
    ]
