# Generated by Django 5.0.6 on 2024-06-19 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sistema", "0003_ata_valor_total_ata"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pedido",
            old_name="quantidade_pedida",
            new_name="quantidade",
        ),
        migrations.RenameField(
            model_name="pedido",
            old_name="valor_total_pedido",
            new_name="valor_total",
        ),
        migrations.RemoveField(
            model_name="ata",
            name="valor_total_ata",
        ),
        migrations.RemoveField(
            model_name="item",
            name="quantidade_restante",
        ),
        migrations.RemoveField(
            model_name="pedido",
            name="produto",
        ),
        migrations.AddField(
            model_name="item",
            name="quantidade_restate",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="itens",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pedidos",
                to="sistema.item",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Resumo",
        ),
    ]
