# Generated by Django 5.0.6 on 2024-06-19 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produtos", "0001_initial"),
        ("sistema", "0004_rename_quantidade_pedida_pedido_quantidade_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pedido",
            old_name="quantidade",
            new_name="quantidade_pedida",
        ),
        migrations.RenameField(
            model_name="pedido",
            old_name="valor_total",
            new_name="valor_total_pedido",
        ),
        migrations.RemoveField(
            model_name="item",
            name="quantidade_restate",
        ),
        migrations.RemoveField(
            model_name="pedido",
            name="itens",
        ),
        migrations.AddField(
            model_name="ata",
            name="valor_total_ata",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="quantidade_restante",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="produto",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="produtos.produto",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Resumo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resumo", models.TextField()),
                (
                    "ata",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sistema.ata"
                    ),
                ),
            ],
        ),
    ]
