# Generated by Django 5.0.6 on 2024-06-20 23:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sistema", "0005_rename_quantidade_pedido_quantidade_pedida_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ata",
            name="valor_total_ata",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
    ]
