# Generated by Django 5.0.6 on 2024-06-22 00:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sistema", "0006_alter_ata_valor_total_ata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="quantidade",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
    ]
