# Generated by Django 5.0.6 on 2024-06-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sistema", "0009_pedido_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="ata",
            name="valor_restante",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="ata",
            name="valor_total_pedidos",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
    ]
