# Generated by Django 5.0.6 on 2024-06-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sistema", "0010_ata_valor_restante_ata_valor_total_pedidos"),
    ]

    operations = [
        migrations.CreateModel(
            name="Geral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_total_atas_ganhas",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
        ),
    ]
