# Generated by Django 5.0.6 on 2024-06-23 12:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sistema", "0011_geral"),
    ]

    operations = [
        migrations.AddField(
            model_name="ata",
            name="link_drive",
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pedido",
            name="prazo",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
