# Generated by Django 5.0.6 on 2024-06-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sistema", "0012_ata_link_drive_pedido_prazo"),
    ]

    operations = [
        migrations.AddField(
            model_name="geral",
            name="valor_total_pedidos",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="geral",
            name="valor_total_restante",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
