# Generated by Django 5.0.6 on 2024-06-23 12:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sistema", "0013_geral_valor_total_pedidos_geral_valor_total_restante"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="geral",
            options={"verbose_name_plural": "Geral"},
        ),
        migrations.AlterModelOptions(
            name="item",
            options={"verbose_name_plural": "Itens"},
        ),
    ]
