# Generated by Django 5.0.6 on 2024-06-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sistema", "0014_alter_geral_options_alter_item_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geral",
            name="valor_total_atas_ganhas",
            field=models.DecimalField(
                blank=True, decimal_places=2, editable=False, max_digits=10, null=True
            ),
        ),
    ]
